version: '3'
services:
  nginx:
    image: nginx:1.19.6
    ports:
      - "8082:80"
    depends_on:
      - php-fpm
    volumes:
      - ./containers/nginx/etc/nginx/conf.d:/etc/nginx/conf.d
      - ./code:/var/www/html
  php-fpm:
    image: php:8.0-fpm
    volumes:
      - ./code:/var/www/html
